<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:mcvideouep="urn:3gpp:mcvideo:mcvideoUEConfig:1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:3gpp:mcvideo:mcvideoUEConfig:1.0"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="http://www.w3.org/2001/xml.xsd"/>

  <xs:element name="mcvideo-UE-configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="mcvideo-UE-id" type="mcvideouep:MCVIDEOUEIDType"/>
          <xs:element name="name" type="mcvideouep:NameType"/>
          <xs:element name="anyExt" type="mcvideouep:anyExtType"/>
          <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element name="common" type="mcvideouep:CommonType"/>
        <xs:element name="on-network" type="mcvideouep:On-networkType"/>
        <xs:element name="anyExt" type="mcvideouep:anyExtType"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="domain" type="xs:anyURI" use="required"/>
      <xs:attribute name="XUI-URI" type="xs:anyURI"/>
      <xs:attribute name="Instance-ID-URN" type="xs:anyURI"/>
      <xs:anyAttribute namespace="##any" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="NameType">
    <xs:simpleContent>
      <xs:extension base="xs:token">
        <xs:attribute ref="xml:lang"/>
        <xs:attributeGroup ref="mcvideouep:IndexType"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MCVIDEOUEIDType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Instance-ID-URN" type="xs:anyURI"/>
      <xs:element name="IMEI-range" type="mcvideouep:IMEI-rangeType"/>
      <xs:element name="anyExt" type="mcvideouep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attributeGroup ref="mcvideouep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="IMEI-rangeType">
    <xs:sequence>
      <xs:element name="TAC" type="mcvideouep:tacType"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="SNR" type="mcvideouep:snrType"/>
        <xs:element name="SNR-range" type="mcvideouep:SNR-rangeType"/>
      </xs:choice>
      <xs:element name="anyExt" type="mcvideouep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="mcvideouep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="SNR-rangeType">
    <xs:sequence>
      <xs:element name="Low-SNR" type="mcvideouep:snrType"/>
      <xs:element name="High-SNR" type="mcvideouep:snrType"/>
      <xs:element name="anyExt" type="mcvideouep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="mcvideouep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:simpleType name="tac-baseType">
      <xs:restriction base="xs:decimal">
        <xs:totalDigits value="8"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tacType">
    <xs:simpleContent>
      <xs:extension base="mcvideouep:tac-baseType">
        <xs:attributeGroup ref="mcvideouep:IndexType"/>
        <xs:anyAttribute namespace="##any" processContents="lax"/>
    </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="snr-baseType">
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="6"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="snrType">
    <xs:simpleContent>
      <xs:extension base="mcvideouep:snr-baseType">
        <xs:attributeGroup ref="mcvideouep:IndexType"/>
        <xs:anyAttribute namespace="##any" processContents="lax"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="CommonType">
    <xs:sequence>
      <xs:element name="MCVIDEO-Private-Call">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Max-Simul-Call-Nc10" type="xs:positiveInteger"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="MCVIDEO-Group-Call">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Max-Simul-Call-Nc4" type="xs:positiveInteger"/>
            <xs:element name="Max-Simul-Trans-Nc5" type="xs:positiveInteger"/>
            <xs:element name="Prioritized-MCVIDEO-Group">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="MCVIDEO-Group-Priority" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="MCVIDEO-Group-ID" type="xs:anyURI"/>
                        <xs:element name="group-priority-hierarchy" type="xs:nonNegativeInteger"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="anyExt" type="mcvideouep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="mcvideouep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="On-networkType">
    <xs:sequence>
      <xs:element name="IPv6Preferred" type="xs:boolean"/>
      <xs:element name="Relay-Service" type="xs:boolean"/>
      <xs:element name="Relayed-MCVIDEO-Group" type="mcvideouep:Relayed-MCVIDEO-GroupType"/>
      <xs:element name="anyExt" type="mcvideouep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="mcvideouep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="Relayed-MCVIDEO-GroupType">
    <xs:sequence>
      <xs:element name="MCVIDEO-Group-ID" type="xs:anyURI"/>
      <xs:element name="Relay-Service-Code" type="xs:string"/>
      <xs:element name="anyExt" type="mcvideouep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:attributeGroup name="IndexType">
    <xs:attribute name="index" type="xs:token"/>
  </xs:attributeGroup>

  <xs:complexType name="anyExtType">
    <xs:sequence>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
