#!/bin/bash
# 단말 SDK Android 네이티브 빌드 — 엔진(ext/pjproject) + 코어(sdk/core) → 두 AAR 모듈의 산출물.
#   정본: docs/design/features/ue_sdk.md §3·§8, docs/design/features/android_dispatch_tablet.md §2.1·§2.2.
#   소스 정본은 ext/pjproject 트리 자체이며 이 스크립트는 패치를 적용하지 않는다(upstream clone·sed 패치
#   단계 없음). 수정은 트리에서 직접 하고 커밋한다.
#
# 산출물은 **모듈 둘**로 갈라 배치한다(android_dispatch_tablet.md §2.2 엔진 단일화):
#   sdk/android/cimsue-engine/  org.pjsip.**(SWIG) + libpjsua2.so   ← android/core 가 쓴다(기존 앱)
#   sdk/android/cimsue/         com.cims.ue.sdk.jni.*(SWIG) + libcimsue.so ← 관제 태블릿이 쓴다
# 둘 다 libc++_shared.so 를 각자 싣는다 — 한 앱이 두 모듈을 같이 쓰지 않으므로 충돌하지 않는다.
# 생성물은 커밋하지 않는다(.gitignore).
#
# 전제(WSL2/Ubuntu 빌드 머신, android_ue_m1_pjsip_integration.md §2.2):
#   ANDROID_NDK_ROOT  NDK 경로 (r27+)
#   OPENSSL_PREFIX    Android arm64 정적 OpenSSL (m1_build_openssl.sh 산출, 기본 ~/opt/openssl-android-arm64)
#   swig, python3, JDK 가 PATH 에 있을 것. ~/.m1env 가 있으면 source 한다(m1_provision.sh 산출).
#
# 사용: sdk/android/build-native.sh [--no-install] [--abi arm64-v8a] [--platform 28] [--engine-only]
#   --no-install    산출물을 AAR 모듈에 배치하지 않는다(빌드만 확인)
#   --engine-only   엔진(pjproject)만 — 코어·cimsue 바인딩 단계를 건너뛴다
set -e -o pipefail
[ -f ~/.m1env ] && source ~/.m1env

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PJ_DIR="$ROOT/ext/pjproject"
CONFIG_SITE="$ROOT/sdk/engine/config_site/android.h"
ENGINE_MOD="$ROOT/sdk/android/cimsue-engine"          # :cimsue-engine — org.pjsip.**
CORE_MOD="$ROOT/sdk/android/cimsue"                   # :cimsue — com.cims.ue.sdk.*
OUT_JNI_BASE="${OUT_JNI:-$ENGINE_MOD/src/main/jniLibs}"
OUT_JAVA="${OUT_JAVA:-$ENGINE_MOD/src/main/java}"
INSTALL=1
ENGINE_ONLY=0
export TARGET_ABI="${TARGET_ABI:-arm64-v8a}"
export APP_PLATFORM="${APP_PLATFORM:-28}"
while [ $# -gt 0 ]; do
  case "$1" in
    --no-install) INSTALL=0 ;;
    --engine-only) ENGINE_ONLY=1 ;;
    --abi) TARGET_ABI="$2"; shift ;;
    --platform) APP_PLATFORM="$2"; shift ;;
    *) echo "unknown arg: $1"; exit 2 ;;
  esac; shift
done

: "${ANDROID_NDK_ROOT:?ANDROID_NDK_ROOT 필요}"
OPENSSL_PREFIX="${OPENSSL_PREFIX:-$HOME/opt/openssl-android-arm64}"
# TLS transport 는 OpenSSL 을 요구한다. 부재 시 configure 가 TLS 를 조용히 끄므로 먼저 확인한다.
test -f "$OPENSSL_PREFIX/lib/libssl.a" || { echo "!! OpenSSL for Android 없음: $OPENSSL_PREFIX (m1_build_openssl.sh 먼저)"; exit 1; }
test -f "$PJ_DIR/pjmedia/src/pjmedia-codec/and_aud_mediacodec.cpp" || { echo "!! ext/pjproject 트리 이상 (and_aud_mediacodec.cpp 없음)"; exit 1; }

cd "$PJ_DIR"
echo "=== [1] config_site.h ← $CONFIG_SITE (플랫폼 파일 펼침) ==="
# 컴파일러에는 #include 한 줄이면 되지만 SWIG 는 pjsua2.i 의 `%import "pj/config_site.h"` 안의 #include 를
#   따라가지 않는다 — 그러면 PJMEDIA_STREAM_ENABLE_KA 등 정본 매크로를 못 봐 StreamInfo 의 KA 필드처럼
#   매크로로 게이트된 멤버가 Java 바인딩에서 빠진다(.so 와 불일치). 정본 파일 내용을 그대로 펼쳐 생성한다
#   (common.h 는 플랫폼 파일이 include 하는 자리에 인라인). 정본은 여전히 sdk/engine/config_site/*.h 다.
python3 - "$CONFIG_SITE" > pjlib/include/pj/config_site.h <<'PY'
import os, re, sys
plat = sys.argv[1]; d = os.path.dirname(plat)
src = open(plat, encoding="utf-8").read()
def inline(m):
    name = m.group(1); body = open(os.path.join(d, name), encoding="utf-8").read()
    return "/* ---- %s (펼침) ---- */\n%s\n/* ---- end %s ---- */" % (name, body, name)
src = re.sub(r'^#include "([^"]+)"[ \t]*$', inline, src, flags=re.M)
print("/* generated by sdk/android/build-native.sh from %s — 정본은 sdk/engine/config_site/, 수정 금지 */" % plat)
print(src)
PY
grep -c "^#define" pjlib/include/pj/config_site.h | sed 's/^/config_site.h defines: /'

echo "=== [2] configure-android + make ($TARGET_ABI, platform $APP_PLATFORM) ==="
./configure-android --use-ndk-cflags --with-ssl="$OPENSSL_PREFIX" 2>&1 | tail -30
make dep 2>&1 | tail -3
make clean >/dev/null 2>&1 || true
make -j"$(nproc)" 2>&1 | tail -15
echo "=== native build DONE ==="

echo "=== [3] SWIG Java 바인딩 ==="
cd pjsip-apps/src/swig
# swig/java 의 규칙은 ①libpjsua2.so 가 pjsua2_wrap.o 만, ②pjsua2_wrap.cpp 가 .i/헤더 몇 개만 의존한다 —
#   정적 .a 나 config_site.h 가 바뀌어도 재링크·SWIG 재생성을 건너뛴다(엔진 수정·매크로 게이트 멤버가
#   .so/Java 에 반영되지 않음). 생성물은 수십 초라 매번 지우고 다시 만든다. java 만 빌드한다(csharp/maui
#   산출물은 트리를 더럽힐 뿐 쓰지 않는다).
make -C java clean >/dev/null 2>&1 || true
make LANG=java 2>&1 | tail -25

echo "=== [4] 산출물 ==="
# swig/java 의 Android 산출물 경로는 고정이다 — find 는 샘플 앱(app-kotlin)·클래스 출력(output/)의
#   같은 이름 디렉터리를 먼저 집어 .java 가 없는 곳을 고를 수 있다.
JNIDIR="$PJ_DIR/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/$TARGET_ABI"
JAVADIR="$PJ_DIR/pjsip-apps/src/swig/java/android/pjsua2/src/main/java/org/pjsip/pjsua2"
[ -f "$JNIDIR/libpjsua2.so" ] && ls "$JAVADIR"/*.java >/dev/null 2>&1 || { echo "!! SWIG 산출물 없음 ($JNIDIR, $JAVADIR)"; exit 1; }
if [ ! -f "$JNIDIR/libc++_shared.so" ]; then
  CXXSO=$(find "$ANDROID_NDK_ROOT" -path "*aarch64-linux-android/libc++_shared.so" | head -1)
  cp "$CXXSO" "$JNIDIR/" && echo "libc++_shared.so copied from NDK"
fi
file "$JNIDIR/libpjsua2.so" | grep -q aarch64 && echo "ABI=arm64 OK"
ls -la "$JNIDIR"; echo "java: $JAVADIR ($(ls "$JAVADIR" | wc -l) files)"

if [ "$INSTALL" = 1 ]; then
  echo "=== [5] 엔진 배치 → :cimsue-engine ($OUT_JNI_BASE/$TARGET_ABI, $OUT_JAVA) ==="
  # 소스셋을 통째로 비우고 다시 채운다 — 엔진 구성이 바뀌어 사라진 클래스가 남으면 .so 와 어긋난다.
  rm -rf "$OUT_JAVA/org" "$OUT_JNI_BASE/$TARGET_ABI"
  mkdir -p "$OUT_JNI_BASE/$TARGET_ABI" "$OUT_JAVA/org/pjsip/pjsua2"
  cp -f "$JNIDIR"/libpjsua2.so "$JNIDIR"/libc++_shared.so "$OUT_JNI_BASE/$TARGET_ABI/"
  cp -f "$JAVADIR"/*.java "$OUT_JAVA/org/pjsip/pjsua2/"
  cp -f "$(dirname "$JAVADIR")"/PjCamera*.java "$OUT_JAVA/org/pjsip/" 2>/dev/null || true
fi

if [ "$ENGINE_ONLY" = 1 ]; then
  echo "=== --engine-only — 코어 단계 건너뜀 ==="
else
  echo "=== [6] 코어 libcimsue.so + cimsue SWIG 바인딩 (NDK CMake) ==="
  # 래퍼가 ext/pjproject/build.mak 에 툴체인·링크 목록을 물어보므로 위 [2] 단계가 선행이다.
  CORE_BUILD="${CORE_BUILD:-$ROOT/build-android}"
  command -v cmake >/dev/null || { echo "!! cmake 없음"; exit 1; }
  cmake -S "$ROOT/sdk/android" -B "$CORE_BUILD" \
        -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
        -DANDROID_ABI="$TARGET_ABI" -DANDROID_PLATFORM="android-$APP_PLATFORM" \
        -DANDROID_STL=c++_shared \
        -DJAVA_OUT_DIR="$CORE_MOD/src/swig/java" 2>&1 | tail -8
  cmake --build "$CORE_BUILD" -j"$(nproc)" 2>&1 | tail -8
  test -f "$CORE_BUILD/libcimsue.so" || { echo "!! libcimsue.so 없음"; exit 1; }
  file "$CORE_BUILD/libcimsue.so" | grep -q aarch64 && echo "libcimsue.so ABI=arm64 OK"

  # ── 바인딩 자기검사 — S1-UE-ANDROID-BIND (android_dispatch_tablet.md §9) ──
  JNI_JAVA="$CORE_MOD/src/swig/java/com/cims/ue/sdk/jni"
  # ① Java 가 아예 없으면 .so 만 최신인 반쪽 산출물이다. "0개" 를 통과로 세지 않는다.
  N_JAVA=$(ls "$JNI_JAVA"/*.java 2>/dev/null | wc -l)
  [ "$N_JAVA" -gt 0 ] || { echo "!! SWIG Java 산출물 없음 ($JNI_JAVA) — .so 만 있는 AAR 이 된다"; exit 1; }
  # ② 불투명 타입이 남으면 앱이 쓸 수 없다.
  N_SWIGTYPE=$(ls "$JNI_JAVA" | grep -c '^SWIGTYPE_' || true)
  [ "$N_SWIGTYPE" = 0 ] || { echo "!! SWIGTYPE_p_* 잔존 — cimsue.i 의 %template/%ignore 를 보완할 것"; exit 1; }
  # ③ 이진 본문이 String 으로 새면 녹취(MP4/AAC)가 첫 NUL 에서 잘린다 — 생성 코드로 확인한다.
  grep -q 'public byte\[\] getBody' "$JNI_JAVA/HttpResult.java" || {
      echo "!! HttpResult.body 가 byte[] 가 아니다 — cimsue.i 의 이진 typemap 이 빠졌다"; exit 1; }
  awk '/HttpResult_1body_1get/,/^}/' "$CORE_BUILD/cimsue_wrap.cpp" | grep -q 'NewByteArray' || {
      echo "!! HttpResult.body 게터가 길이 기반 변환이 아니다"; exit 1; }
  awk '/HttpResult_1body_1get/,/^}/' "$CORE_BUILD/cimsue_wrap.cpp" | grep -q 'NewStringUTF' && {
      echo "!! HttpResult.body 게터가 NewStringUTF 를 쓴다 — NUL 에서 잘린다"; exit 1; }
  echo "cimsue Java: $N_JAVA 개, 불투명 타입 0, HttpResult.body=byte[] OK"

  if [ "$INSTALL" = 1 ]; then
    echo "=== [7] 코어 배치 → :cimsue ($CORE_MOD/src/main/jniLibs/$TARGET_ABI) ==="
    rm -rf "$CORE_MOD/src/main/jniLibs/$TARGET_ABI"
    mkdir -p "$CORE_MOD/src/main/jniLibs/$TARGET_ABI"
    cp -f "$CORE_BUILD/libcimsue.so" "$CORE_MOD/src/main/jniLibs/$TARGET_ABI/"
    # libc++_shared 는 두 모듈이 각자 싣는다(한 앱이 둘을 같이 쓰지 않는다 — §2.2).
    cp -f "$JNIDIR/libc++_shared.so" "$CORE_MOD/src/main/jniLibs/$TARGET_ABI/"
    ls -la "$CORE_MOD/src/main/jniLibs/$TARGET_ABI/"
  fi
fi

echo "=== 트리 청결 확인 (정본 트리는 빌드 후에도 변경이 없어야 한다) ==="
cd "$ROOT" && git status --short ext/pjproject | head -20
echo "=== BUILD ALL DONE ==="
