! CSP (VoLTE SIP server) HA configuration
! Generated by `cims.sh ha config` from this template (DO NOT EDIT generated /etc/keepalived/keepalived.conf manually)
! VRRP VRID = 52 for CSP group

global_defs {
    enable_script_security
    script_user root
    router_id ${NODE_NAME}_csp
}

vrrp_script check_csp {
    script   "${HA_DIR}/check_csp.sh"
    interval 2
    timeout  3
    rise     2
    fall     2
}

vrrp_instance VI_CSP {
    state               ${INITIAL_STATE}
    interface           ${INTERFACE}
    virtual_router_id   52
    priority            ${PRIORITY_CSP}
    advert_int          1
    nopreempt
    unicast_src_ip      ${LOCAL_IP}
    unicast_peer {
        ${PEER_IP}
    }
    authentication {
        auth_type PASS
        auth_pass ${AUTH_PASS}
    }
    virtual_ipaddress {
        ${VIP_CSP}/${VIP_MASK} dev ${INTERFACE}
    }
    track_script {
        check_csp
    }
    notify "${HA_DIR}/notify_csp.sh"
}
